import { Product, Category } from './types';

export const translations = {
  az: {
    appName: "MEMİ QƏBƏLƏ",
    appSubtitle: "Premium E-commerce & İdarəetmə Platforması",
    heroTitle: "2-ci Əl və Yeni Avropa Brendləri",
    heroSubtitle: "Avropadan seçilmiş premium geyim, ayaqqabı və aksessuarların dərhal qapınıza çatdırılması",
    searchPlaceholder: "Məhsul adı və ya kateqoriya ilə canlı axtarış...",
    categoryAll: "Bütün Kateqoriyalar",
    categoryGeyim: "Geyim",
    categoryAksesuar: "Aksesuarlar",
    categoryAyaqqabi: "Ayaqqabılar",
    categoryNemet: "Xüsusi Məhsullar",
    cartTitle: "🛒 Səbətiniz",
    cartEmpty: "Səbətiniz hal-hazırda boşdur.",
    cartTotal: "Cəmi Ödəniş:",
    cartOrderBtn: "Alışı Tamamla",
    orderSuccessMsg: "Özünə dəyər verməyi bacaran insan! Sifarişiniz hazırlanır. Əmin olun ki, etdiyiniz bu sifariş sizə ən tez zamanda və güvənli bir şəkildə əlinizə çatacaq. Qeyd edək ki, məhsullarımızın geri qaytarılması yoxdur. Memi Qəbələ hər zaman sizin xidmətinizdədir. Əsl Avropa brendlərini Memi Qəbələ sizlər üçün yaxın etdi.",
    orderSubmitTitle: "Sifarişi Tamamlayın",
    nameLabel: "Adınız və Soyadınız:",
    phoneLabel: "Telefon Nömrəniz:",
    addressLabel: "Çatdırılma Ünvanı (Məs. Qəbələ, Bakı rayonları):",
    paymentMethodLabel: "Ödəniş Üsulu:",
    paymentCash: "Qapıda Nəğd / Kuryerə Ödəniş",
    paymentCard: "Onlayn Kartla Ödəniş",
    cancelBtn: "İmtina Et",
    orderConfirmBtn: "Sifarişi Təsdiqlə",
    adminTitle: "İdarəçi Girişi",
    adminLoginBtn: "Giriş Et",
    adminPasswordLabel: "Giriş Şifrəsi:",
    adminPasswordPlaceholder: "Daxil edin...",
    adminWrongPassword: "Səhv şifrə!",
    adminDashboardTitle: "👨‍💼 Müdir İdarəetmə Paneli",
    addProductTitle: "📦 Yeni Məhsul Əlavə Et",
    productNameAzLabel: "Adı (AZ):",
    productNameEnLabel: "Adı (EN):",
    productNameRuLabel: "Adı (RU):",
    productDescAzLabel: "Təsviri (AZ):",
    productPriceLabel: "Qiyməti (₼):",
    productCategoryLabel: "Kateqoriya:",
    productImageLabel: "Şəkil Linki (URL):",
    productStockLabel: "Stok Sayı:",
    productSaveBtn: "Bazaya Yaz və Vitrinə At",
    ordersTitle: "📥 Gələn Sifarişlər",
    orderId: "Sifariş İD",
    orderCustomer: "Müştəri",
    orderItems: "Məhsullar",
    orderTotal: "Toplam",
    statusLabel: "Status:",
    statusYeni: "Yeni Sifariş",
    statusGozleyir: "Gözləmədə",
    statusTamamlandi: "Tamamlandı",
    statusLegv: "Ləğv edildi",
    logoutBtn: "Çıxış",
    addToCartBtn: "Səbətə At",
    quickOrderBtn: "Dərhal Sifariş Et",
    resetDbBtn: "Məlumatları Sıfırla",
    resetDbConfirm: "Baza məlumatlarını sıfırlamağa əminsiniz?",
    newProductSuccess: "Məhsul əlavə olundu!",
    productsHeader: "🔥 Seçilən Veb Məhsulları",
    stockStatusLabel: "Stok durumu:",
    inStock: "Stokda Var",
    outOfStock: "Tükəndi",
    deleteProductBtn: "Məhsulu Sil",
    deleteProductConfirm: "Bu məhsulu silməyə əminsiniz?",
    historyTitle: "📜 Sistem Tarixcəsi",
    historyEmpty: "Əməliyyat tapılmadı.",
    changePasswordTitle: "🔐 Şifrəni Yenilə",
    oldPasswordLabel: "Cari Şifrə:",
    newPasswordLabel: "Yeni Şifrə:",
    confirmPasswordLabel: "Yeni Şifrə Təkrarı:",
    passwordChangeSuccess: "Şifrə yeniləndi!",
    passwordMismatch: "Şifrələr uyuşmur!",
    wrongOldPassword: "Cari şifrə yanlışdır!",
    cleanHistoryBtn: "Tarixcəni Təmizlə",
    cleanHistoryConfirm: "Sistem tarixcəsi tamamilə silinsin?",
    productSizeLabel: "Ölçü (S, M, L, XL, və ya 38, 39, 40):",
    sizeLabel: "Ölçü",
    zoomInstruction: "Yaxınlaşdırmaq üçün klikləyin.",
    zoomIn: "Yaxınlaşdır (+)",
    zoomOut: "Uzaqlaşdır (-)",
    resetZoom: "Sıfırla"
  },
  en: {
    appName: "MEMI QABALA",
    appSubtitle: "Premium E-commerce & Store Management Platform",
    heroTitle: "Second-Hand & Brand New European Clothing",
    heroSubtitle: "Premium curated apparel, footwear, and accessories from Europe delivered straight to your door",
    searchPlaceholder: "Live search by product name or category...",
    categoryAll: "All Categories",
    categoryGeyim: "Clothing",
    categoryAksesuar: "Accessories",
    categoryAyaqqabi: "Shoes",
    categoryNemet: "Special Products",
    cartTitle: "🛒 Your Cart",
    cartEmpty: "Your cart is currently empty.",
    cartTotal: "Total Amount:",
    cartOrderBtn: "Complete Order",
    orderSuccessMsg: "Special value-driven individual! Your order is being prepared. Rest assured that this order will reach you as quickly and securely as possible. Please note that returns are not possible. Memi Qabala is always at your service. Authentic European brand products are brought closer to you by Memi Qabala.",
    orderSubmitTitle: "Complete Your Order",
    nameLabel: "Your Name & Surname:",
    phoneLabel: "Phone Number:",
    addressLabel: "Delivery Address (Qabala, Baku, etc):",
    paymentMethodLabel: "Payment Method:",
    paymentCash: "Cash on Delivery",
    paymentCard: "Online Card Payment",
    cancelBtn: "Cancel",
    orderConfirmBtn: "Confirm Order",
    adminTitle: "System Admin Login",
    adminLoginBtn: "Login",
    adminPasswordLabel: "Access Password:",
    adminPasswordPlaceholder: "Enter password...",
    adminWrongPassword: "Wrong password!",
    adminDashboardTitle: "👨‍💼 Admin Dashboard Manager",
    addProductTitle: "📦 Add New Product",
    productNameAzLabel: "Name (AZ):",
    productNameEnLabel: "Name (EN):",
    productNameRuLabel: "Name (RU):",
    productDescAzLabel: "Description (AZ):",
    productPriceLabel: "Price (₼):",
    productCategoryLabel: "Category:",
    productImageLabel: "Image Link (URL):",
    productStockLabel: "Stock Count:",
    productSaveBtn: "Save to Showcase Live",
    ordersTitle: "📥 Manage Incoming Orders",
    orderId: "Order ID",
    orderCustomer: "Customer Info",
    orderItems: "Items / List",
    orderTotal: "Total Price",
    statusLabel: "Status:",
    statusYeni: "New Order",
    statusGozleyir: "Pending",
    statusTamamlandi: "Completed",
    statusLegv: "Cancelled",
    logoutBtn: "Logout Admin",
    addToCartBtn: "Add to Cart",
    quickOrderBtn: "Quick Order",
    resetDbBtn: "Reset Database Defaults",
    resetDbConfirm: "Restore the database to initial seed defaults?",
    newProductSuccess: "Product successfully saved to database!",
    productsHeader: "🔥 Exquisite Products Offered",
    stockStatusLabel: "Stock Status:",
    inStock: "In Stock",
    outOfStock: "Out of Stock",
    deleteProductBtn: "Delete",
    deleteProductConfirm: "Delete this product?",
    historyTitle: "📜 System Event Logs",
    historyEmpty: "No activity records found yet.",
    changePasswordTitle: "🔐 Change Password",
    oldPasswordLabel: "Current Password:",
    newPasswordLabel: "New Password:",
    confirmPasswordLabel: "Confirm Password:",
    passwordChangeSuccess: "Successfully updated password!",
    passwordMismatch: "New passwords do not match!",
    wrongOldPassword: "Current password is incorrect!",
    cleanHistoryBtn: "Clear Logs",
    cleanHistoryConfirm: "Are you sure you want to clear history records?",
    productSizeLabel: "Size (S, M, L, XL, or 38, 39, 40):",
    sizeLabel: "Size",
    zoomInstruction: "Click to zoom.",
    zoomIn: "Zoom In (+)",
    zoomOut: "Zoom Out (-)",
    resetZoom: "Reset"
  },
  ru: {
    appName: "МЕМИ ГАБАЛА",
    appSubtitle: "Премиум Электронная Коммерция & Панель Управления",
    heroTitle: "Секонд-хенд и новые европейские бренды",
    heroSubtitle: "Премиальная одежда, обувь и аксессуары из Европы с быстрой доставкой на дом",
    searchPlaceholder: "Живой поиск по названию или категории...",
    categoryAll: "Все Категории",
    categoryGeyim: "Одежда",
    categoryAksesuar: "Аксессуары",
    categoryAyaqqabi: "Обувь",
    categoryNemet: "Особые Товары",
    cartTitle: "🛒 Ваша Корзина",
    cartEmpty: "Ваша корзина пуста.",
    cartTotal: "Итого к оплате:",
    cartOrderBtn: "Оформить Заказ",
    orderSuccessMsg: "Человек, который умеет ценить себя! Ваш заказ готовится. Будьте уверены, что этот заказ будет доставлен вам максимально быстро и безопасно. Обратите внимание, что возврата у нас нет. Memi Qabala всегда к вашим услугам. Настоящие европейские бренды стали ближе к вам благодаря Memi Qabala.",
    orderSubmitTitle: "Завершение Заказа",
    nameLabel: "Ваше Имя и Фамилия:",
    phoneLabel: "Номер Телефона:",
    addressLabel: "Адрес Доставки (Габала, Баку и др):",
    paymentMethodLabel: "Способ Оплаты:",
    paymentCash: "Наличными курьеру при получении",
    paymentCard: "Онлайн оплата картой",
    cancelBtn: "Отмена",
    orderConfirmBtn: "Подтвердить Заказ",
    adminTitle: "Вход в Панель",
    adminLoginBtn: "Войти",
    adminPasswordLabel: "Пароль Доступа:",
    adminPasswordPlaceholder: "Введите пароль...",
    adminWrongPassword: "Неверный пароль!",
    adminDashboardTitle: "👨‍💼 Панель Управления Директора",
    addProductTitle: "📦 Добавить Новый Товар",
    productNameAzLabel: "Название (AZ):",
    productNameEnLabel: "Название (EN):",
    productNameRuLabel: "Название (RU):",
    productDescAzLabel: "Описание (AZ):",
    productPriceLabel: "Цена (₼):",
    productCategoryLabel: "Категория:",
    productImageLabel: "Ссылка на Картинку (URL):",
    productStockLabel: "Количество:",
    productSaveBtn: "Сохранить на Витрину",
    ordersTitle: "📥 Входящие Заказы",
    orderId: "ID Заказа",
    orderCustomer: "Покупатель",
    orderItems: "Товары",
    orderTotal: "Сумма",
    statusLabel: "Статус:",
    statusYeni: "Новый Заказ",
    statusGozleyir: "В Ожидании",
    statusTamamlandi: "Завершен",
    statusLegv: "Отменен",
    logoutBtn: "Выйти",
    addToCartBtn: "В Корзину",
    quickOrderBtn: "Купить Сейчас",
    resetDbBtn: "Сбросить Базу",
    resetDbConfirm: "Сбросить базу данных к начальным настройкам?",
    newProductSuccess: "Товар успешно добавлен!",
    productsHeader: "🔥 Избранные Предложения",
    stockStatusLabel: "Наличие:",
    inStock: "В Наличии",
    outOfStock: "Нет в Наличии",
    deleteProductBtn: "Удалить",
    deleteProductConfirm: "Удалить этот товар?",
    historyTitle: "📜 Системный Журнал",
    historyEmpty: "Записи событий отсутствуют.",
    changePasswordTitle: "🔐 Сменить Пароль",
    oldPasswordLabel: "Текущий Пароль:",
    newPasswordLabel: "Новый Пароль:",
    confirmPasswordLabel: "Повторите Пароль:",
    passwordChangeSuccess: "Пароль успешно изменен!",
    passwordMismatch: "Новые пароли не совпадают!",
    wrongOldPassword: "Текущий пароль введен неверно!",
    cleanHistoryBtn: "Очистить Журнал",
    cleanHistoryConfirm: "Вы уверены, что хотите очистить журнал истории?",
    productSizeLabel: "Размер (S, M, L, XL, или 38, 39, 40):",
    sizeLabel: "Размер",
    zoomInstruction: "Нажмите для увеличения.",
    zoomIn: "Увеличить (+)",
    zoomOut: "Уменьшить (-)",
    resetZoom: "Сбросить"
  }
};

export const initialSeedProducts: Product[] = [
  {
    id: '1001',
    title_az: 'Avropa Vintage Dəri Gödəkçə',
    title_en: 'European Vintage Leather Jacket',
    title_ru: 'Европейская Винтажная Кожаная Куртка',
    description_az: 'Həqiqi yüksək keyfiyyətli dəridən, klassik kəsimli, Avropadan gətirilmiş premium vintage gödəkçə.',
    price: 120.00,
    category: 'geyim',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80',
    stock: 5,
    size: 'M, L, XL',
    discountPercent: 0
  },
  {
    id: '1002',
    title_az: 'İtalyan İpək Don',
    title_en: 'Italian Silk Dress',
    title_ru: 'Итальянское Шелковое Платье',
    description_az: 'Yumşaq təbii ipəkdən zərif yay donu. Premium italyan markasından zərif dizayn.',
    price: 85.00,
    category: 'geyim',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80',
    stock: 3,
    size: 'S, M',
    discountPercent: 0
  },
  {
    id: '1003',
    title_az: 'Yun Payız Palto',
    title_en: 'Woolen Autumn Coat',
    title_ru: 'Шерстяное Осеннее Пальто',
    description_az: '100% təbii yundan, soyuq havalar üçün isti və şık, Avropa fabriki istehsalı olan bej palto.',
    price: 155.00,
    category: 'geyim',
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
    stock: 2,
    size: 'M, L',
    discountPercent: 0
  },
  {
    id: '1004',
    title_az: 'Dizayner Saffiano Dəri Çantası',
    title_en: 'Designer Saffiano Leather Handbag',
    title_ru: 'Дизайнерская Сумка Из Кожи Сафьяно',
    description_az: 'Yüksək səviyyəli dəb kolleksiyasından cızıqlara dayanıqlı Saffiano premium çanta.',
    price: 210.00,
    category: 'aksesuar',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80',
    stock: 4,
    size: 'Standart',
    discountPercent: 0
  },
  {
    id: '1005',
    title_az: 'Süet Yarımboğaz Ayaqqabı',
    title_en: 'Premium Suede Anklet Boots',
    title_ru: 'Премиальные Замшевые Ботильоны',
    description_az: 'Yumşaq təbii süetdən, rahat dabanlı və son dərəcə zərif Avropa üslublu ayaqqabı.',
    price: 95.00,
    category: 'ayaqqabi',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
    stock: 6,
    size: '37, 38, 39',
    discountPercent: 0
  },
  {
    id: '1006',
    title_az: 'Xalis Qəbələ Dağ Balı (1 kq)',
    title_en: 'Pure Gabala Mountain Honey (1 kg)',
    title_ru: 'Чистый Горный Мед Габалы (1 кг)',
    description_az: 'Qəbələnin hündür dağ yamaclarında yığılmış, 100% təbii, müalicəvi xalis çiçək balı.',
    price: 25.00,
    category: 'nemet',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80',
    stock: 15,
    size: '1 kq',
    discountPercent: 0
  }
];

export const initialCategories: Category[] = [
  { id: 'geyim', name_az: 'Geyim', name_en: 'Clothing', name_ru: 'Одежда', emoji: '👕' },
  { id: 'aksesuar', name_az: 'Aksessuarlar', name_en: 'Accessories', name_ru: 'Аксессуары', emoji: '👜' },
  { id: 'ayaqqabi', name_az: 'Ayaqqabılar', name_en: 'Shoes', name_ru: 'Обувь', emoji: '👟' },
  { id: 'nemet', name_az: 'Seçilmiş Nematlar', name_en: 'Qabala Delicacies', name_ru: 'Особые Товары', emoji: '🍯' }
];
